# Generated by Django 4.1 on 2022-11-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_questions_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profilepics'),
        ),
    ]
